helmfile/private-network-ibft-automated/README.md
helmfile/private-network-ibft-automated/helmfile.d/00-genesis-helmfile.yaml
helmfile/private-network-ibft-automated/helmfile.d/01-bootnode-helmfile.yaml
helmfile/private-network-ibft-automated/helmfile.yaml
helmfile/private-network-ibft-automated/pantheon-genesis/.helmignore
helmfile/private-network-ibft-automated/pantheon-genesis/Chart.yaml
helmfile/private-network-ibft-automated/pantheon-genesis/templates/_helpers.tpl
helmfile/private-network-ibft-automated/pantheon-genesis/templates/configmap.yaml
helmfile/private-network-ibft-automated/pantheon-genesis/templates/genesis-job.yaml
helmfile/private-network-ibft-automated/pantheon-genesis/templates/role-binding.yaml
helmfile/private-network-ibft-automated/pantheon-genesis/values.yaml
helmfile/private-network-ibft-automated/pantheon-node/.helmignore
helmfile/private-network-ibft-automated/pantheon-node/Chart.yaml
helmfile/private-network-ibft-automated/pantheon-node/templates/_helpers.tpl
helmfile/private-network-ibft-automated/pantheon-node/templates/configmap_config.yaml
helmfile/private-network-ibft-automated/pantheon-node/templates/configmap_permissions.yaml
helmfile/private-network-ibft-automated/pantheon-node/templates/ingress_http.yaml
helmfile/private-network-ibft-automated/pantheon-node/templates/ingress_ws.yaml
helmfile/private-network-ibft-automated/pantheon-node/templates/secret-bootnode-job.yaml
helmfile/private-network-ibft-automated/pantheon-node/templates/secret-bootnode.yaml
helmfile/private-network-ibft-automated/pantheon-node/templates/secret-validators.yaml
helmfile/private-network-ibft-automated/pantheon-node/templates/service.yaml
helmfile/private-network-ibft-automated/pantheon-node/templates/statefulset.yaml
helmfile/private-network-ibft-automated/pantheon-node/values.yaml
helmfile/private-network-ibft-automated/values/bootnode.yaml
helmfile/private-network-ibft-automated/values/genesis.yaml
helmfile/private-network-ibft-automated/values/validator.yaml

Arnaud & Nedim's helmfile deployment

helmfile ibft

---

README.md

updating doco with permissioning details

updating doco with permissioning details

---

helm/private-network-ethash/pantheon/README.md
helm/private-network-ibft/pantheon/README.md
kubectl/private-network-ethash/README.md
kubectl/private-network-ibft/README.md

fixing the path of the arch diagram in the readme

fixing the path of the arch diagram in the readme

---

helm/private-network-ethash/pantheon/README.md
helm/private-network-ibft/pantheon/README.md
kubectl/private-network-ethash/README.md
kubectl/private-network-ibft/README.md

This also allows us to see what the changes will look like should we change the image without it needing to be in Master

Fix all readme image paths for all branches and all forks

---

README.md

updating with a note about minikube default settings

updating with a note about minikube default settings

---

helm/private-network-ibft/besu/README.md

Updated docker image from pegasyseng/besu:develop to hyperledger/besu:develop

Wrong docker image

---

README.md
helm/private-network-ethash/besu/Chart.yaml
helm/private-network-ethash/besu/README.md
helm/private-network-ibft/besu/Chart.yaml
helm/private-network-ibft/besu/README.md
helmfile/private-network-ibft-automated/README.md
helmfile/private-network-ibft-automated/besu-node/Chart.yaml

- updating pegasyseng to hyperledger
Signed-off-by: Joshua Fernandes <joshua.fernandes@consensys.net>

updating pegasyseng to hyperledger

---

helm/ingress/README.md
helm/ingress/ingress-rules.yaml

Ingress controller rules for deployment to cloud. We will be using this for our marketplace offerings - this saves users the cost of a load balancer and provides much better routing capability

Ingress controller rules for deployment to cloud 

---

helm/ingress/README.md
helm/ingress/ingress-rules-besu.yaml
helm/ingress/ingress-rules-grafana.yaml

helm3 requires a repo added before a chart can be deployed

helm3 requires a repo added before a chart can be deployed

---

helmfile/ibft2/charts/besu-genesis/templates/genesis-job.yaml
helmfile/ibft2/charts/besu-genesis/values.yaml

Fix for besu user in the genesis file creation for helmfile. We need to run this job as root to install kubectl and create the genesis file and keys etc

helmfile genesis job run as root to install kubectl and other packages

---

prod/helm/charts/besu-genesis/templates/genesis-job.yaml
prod/helm/charts/besu-genesis/values.yaml
prod/helm/charts/besu-node/templates/node-hooks.yaml
prod/helm/charts/besu-node/values.yaml
prod/helm/charts/goquorum-genesis/templates/genesis-job.yaml
prod/helm/charts/goquorum-genesis/values.yaml
prod/helm/charts/goquorum-node/templates/node-hooks.yaml
prod/helm/charts/goquorum-node/values.yaml
prod/helm/values/bootnode.yml
prod/helm/values/genesis-besu.yml
prod/helm/values/genesis-goquorum.yml
prod/helm/values/reader.yml
prod/helm/values/txnode.yml
prod/helm/values/validator.yml

adding azure subscription id for multi tenancy users

---

helm/README.md
helm/charts/besu-genesis/templates/genesis-job-init.yaml
helm/charts/besu-node/templates/node-hooks-pre-delete.yaml
helm/charts/besu-node/templates/node-hooks-pre-install.yaml
helm/charts/besu-node/templates/node-hooks-service-account.yaml
helm/charts/besu-node/templates/node-statefulset.yaml
helm/charts/besu-node/values.yaml
helm/charts/goquorum-node/templates/node-hooks-pre-install.yaml
helm/values/bootnode.yml
helm/values/genesis-besu.yml
helm/values/reader.yml
helm/values/validator.yml

dynamic bootnodes for besu

---

docker/quorum-k8s-hooks/Dockerfile

Fixes #140 
* remove man workaround
* remove vim install
* remove helm install
* install quorum-genesis-tool
* remove awscli install files

Optimize quorum-k8s-hooks image

---

docker/quorum-k8s-hooks/Dockerfile
helm/charts/besu-genesis/values.yaml
helm/charts/besu-node/values.yaml
helm/charts/goquorum-genesis/values.yaml
helm/charts/goquorum-node/values.yaml

Signed-off-by: Eric Lin <eric.lin@consensys.net>

update qgt to 0.1.7 and qgt-0.1.7 k8s hooks

---

helm/values/explorer-besu.yaml
helm/values/explorer-goquorum.yaml

Signed-off-by: Eric Lin <eric.lin@consensys.net>

update explorer images

---

helm/charts/besu-genesis/templates/genesis-job-init.yaml

Fixed indentation of labels that caused an error during deployment

Fixed indentation of labels

---

helm/charts/besu-node/templates/node-statefulset.yaml
helm/charts/besu-node/values.yaml
helm/charts/goquorum-node/templates/node-statefulset.yaml
helm/charts/goquorum-node/values.yaml
helm/values/bootnode.yml

Closing issue #185: Enable possibility to add custom labels to the besu-node pods without changing manifest files but only by modifying specific values yaml file.

Closing issue #185

---

helm/charts/besu-node/templates/node-hooks-pre-delete.yaml
helm/charts/besu-node/templates/node-hooks-pre-install.yaml
helm/charts/besu-node/templates/node-hooks-service-account.yaml
helm/charts/besu-node/templates/node-service-account.yaml

PR #205 introduced several indentation errors, causing Helm commands to fail while deploying the `besu-node` Chart to EKS.
Fixes #206

fix: besu-node templates

---

helm/README.md
helm/charts/blockscout/templates/blockscout-statefulset.yaml
helm/charts/goquorum-node/templates/node-hooks-service-account.yaml
helm/charts/goquorum-node/templates/node-service-account.yaml

chore: fixed helm install errors

---

helm/charts/besu-node/templates/node-statefulset.yaml

statefulset seems to have an error in it (if condition not correctly formed).

Fixing broken statefulset template

---

README.md
helm/README.md

Enhanced documentation with additional information

Documentation update

---

helm/README.md

Added some observation and log messages to elaborate the installation with Helm

Additional information in Helm deploy
