Consensys/quorum-kubernetes

helmfile/private-network-ibft-automated/besu-genesis/templates/role-binding.yaml
Switched hard coded default namespace for the default sa account to the namespace the helmfile is applying to.
This fixes helmfile applies outside of the default kubernetes namespace.
=> automated ibft namespace fix

kubectl/private-network-ibft-and-orion/README.md
In the Besu chat channel someone is trying to follow the readme of the `private-network-ibft-and-orion` folder and came across a small mistake that was causing some confusion. See Besu chat for the full question and my response. Tried to make it a little more clear in this PR.
Current setup is still running smooth on my side. Good to see other people are trying this setup as well though! :+1:
=> Small readme fix 

kubectl/private-network-clique/deployments/node-deployment.yaml, kubectl/private-network-clique/deployments/validator1-deployment.yaml, kubectl/private-network-clique/deployments/validator2-deployment.yaml, kubectl/private-network-clique/deployments/validator3-deployment.yaml, kubectl/private-network-clique/deployments/validator4-deployment.yaml
I have been looking into the Grafana chart and I noticed that the 500m cpu limit is always hit when the GC is triggered. This results in pod restarts.
=> increase the cpu limit for the clique network

helm/consortium/besu/templates/besu-config-toml-configmap.yaml, helm/consortium/besu/templates/members-besu-config-toml-configmap.yaml, helm/ethash/besu/templates/besu-config-toml-configmap.yaml, helm/ibft2-with-privacy/besu/templates/besu-config-toml-configmap.yaml, helm/ibft2/besu/templates/besu-config-toml-configmap.yaml
if both rpc and ws enabled, in that case besu-node was failed to reach by ingress as rpc and ws has same ports in config.toml
=> websockets failed as rpc and ws has the same ports if ws enabled

kubectl/ibft2/services/validator2-service.yaml
Add missing spaces that cause an error.
=> Fix the invalid validator2-service.ayml kube spec for besu ibft2.

helm/consortium/besu/values.yaml, helm/ethash/besu/values.yaml, helm/ibft2-with-privacy/besu/values.yaml, helm/ibft2/besu/values.yaml, helmfile/ibft2/charts/besu-node/values.yaml, kubectl/clique/statefulsets/node-statefulset.yaml, kubectl/clique/statefulsets/validator1-statefulset.yaml, kubectl/clique/statefulsets/validator2-statefulset.yaml, kubectl/clique/statefulsets/validator3-statefulset.yaml, kubectl/clique/statefulsets/validator4-statefulset.yaml, kubectl/ethash/statefulsets/bootnode1-statefulset.yaml, kubectl/ethash/statefulsets/bootnode2-statefulset.yaml, kubectl/ethash/statefulsets/minernode-statefulset.yaml, kubectl/ethash/statefulsets/node-statefulset.yaml, kubectl/ibft2-with-privacy/statefulsets/node-statefulset.yaml, kubectl/ibft2-with-privacy/statefulsets/node1privacy-statefulset.yaml, kubectl/ibft2-with-privacy/statefulsets/node2privacy-statefulset.yaml, kubectl/ibft2-with-privacy/statefulsets/validator1-statefulset.yaml, kubectl/ibft2-with-privacy/statefulsets/validator2-statefulset.yaml, kubectl/ibft2-with-privacy/statefulsets/validator3-statefulset.yaml, kubectl/ibft2-with-privacy/statefulsets/validator4-statefulset.yaml, kubectl/ibft2/statefulsets/node-statefulset.yaml, kubectl/ibft2/statefulsets/validator1-statefulset.yaml, kubectl/ibft2/statefulsets/validator2-statefulset.yaml, kubectl/ibft2/statefulsets/validator3-statefulset.yaml, kubectl/ibft2/statefulsets/validator4-statefulset.yaml
Now that Besu 1.5.0 is released, we can go back to using 'latest'
Besu 1.5.0 introduces some breaking changes to the docker containers & volume mounts i.e to maintain best security practices, the user:group on the Docker container to besu. More information on the [1.5.0 release page](https://github.com/hyperledger/besu/releases/tag/1.5.0)
=> use the latest tag now that 1.5.0 is out and tagged latest

helmfile/quorum-besu/ibft2/charts/besu-node/templates/http-ingress.yaml
At the moment, after ingress resource is deployed, it is always returning HTTP 503 response.
By having 
```
servicePort: http
```
it cannot find the Endpoint because port 80 is not exposed/not listened by "bootnode-*-besu-node" services. Actual service that is proxied via ingress is exposing 8545 as http rpc port.
It should have
```
servicePort: 8545
```
Used environment for testing:
- AWS infrastructure
- K8s v1.17.13
- quorum-kubernetes deployment with helmfile
=> Fixing bug in (helmfile/ibft2.0) Besu-node http-ingress.yaml

playground/kubectl/quorum-go/ibft/statefulsets/member1-statefulset.yaml, playground/kubectl/quorum-go/ibft/statefulsets/member2-statefulset.yaml, playground/kubectl/quorum-go/ibft/statefulsets/member3-statefulset.yaml, playground/kubectl/quorum-go/ibft/statefulsets/validator1-statefulset.yaml, playground/kubectl/quorum-go/ibft/statefulsets/validator2-statefulset.yaml, playground/kubectl/quorum-go/ibft/statefulsets/validator3-statefulset.yaml, playground/kubectl/quorum-go/ibft/statefulsets/validator4-statefulset.yaml
Fix CLI options for Quorum (member and validator) in the playground.
Quorum cannot start due to incorrect command line options.
If I try the playground in the master branch, it looks like this.
```
$ minikube start --memory 16384 --cpus 6
$ cd playground/kubectl/quorum-go/ibft/
$ ./deploy.sh
$ kubectl -n quorum get pod
NAME           READY   STATUS             RESTARTS      AGE
member1-0      1/2     CrashLoopBackOff   3 (28s ago)   5m10s
member2-0      1/2     CrashLoopBackOff   3 (37s ago)   5m10s
member3-0      1/2     CrashLoopBackOff   3 (41s ago)   5m10s
validator1-0   0/1     CrashLoopBackOff   4 (32s ago)   5m10s
validator2-0   0/1     CrashLoopBackOff   4 (43s ago)   5m10s
validator3-0   0/1     CrashLoopBackOff   4 (32s ago)   5m9s
validator4-0   0/1     CrashLoopBackOff   4 …
```
=> Fix CLI options for Quorum in playground

aws/README.md, aws/templates/cluster.yml, dev/helm/charts/besu-node/templates/node-statefulset.yaml, dev/helm/charts/goquorum-node/templates/node-statefulset.yaml, dev/helm/values/genesis-besu.yml
- Edited eksctl `cluster.yml` to create a new VPC on deployment to have eksctl manage the tags. To use an existing VPC, yaml has been commented out with some comments
- When helm delete is used on AWS or Azure, a subsequent helm install with the same release name should re-use pvc and have access to the previous chain data (supported for besu and goq)
- Updated AWS eksctl deployment README on how to provision the EBS CSI driver 
Signed-off-by: Eric Lin <eric.lin@consensys.net>
=> edit eksctl to create vpc, besu and goq retain and remount on install

helm/charts/besu-node/values.yaml
Hi there,
I re-deployed my test AKS cluster recently to come up to date with the newest version of the helm charts and was unable to perform any transactions due to the default on-chain permissioning of accounts that this PR disables. I'm not sure if this was intentionally set to true but it took a full day for me to figure this out as I've not looked much at on-chain permissioning yet.
This PR addresses this issue that was submitted on the Hyperledger Besu repository: https://github.com/hyperledger/besu/issues/4684
Feel free to deny my PR if this setting was intentional.
Best Regards,
Corey
=> Onchain account permissioning to default disabled

helm/charts/goquorum-node/templates/node-servicemonitor.yaml
I have set up a goquorum prometheus but could not get the metrics for the blockchain node.
The cause was the Label setting in the prometheus operator, so I fixed this.
=> Fix goquorum monitoring servicemonitor matchLabels

helm/charts/besu-node/templates/besu-config-configmap.yaml, helm/charts/besu-node/values.yaml
Closing issue https://github.com/ConsenSys/quorum-kubernetes/issues/180: make number of allowed rpc connections configurable via values.yaml file of besu node helm chart.
=> Closing issue #180

helm/charts/besu-node/values.yaml
Websokcet connection is necessary for Blockscout and any other blockchain service. But, in this helm chart Websocket default value is false. 
This PR related to https://github.com/ConsenSys/quorum-kubernetes/issues/178
Thanks.
=> Update besu-node value of ws enabled to true.

helm/charts/besu-node/templates/node-storage.yaml, helm/charts/besu-node/values.yaml, helm/charts/goquorum-node/templates/node-storage.yaml, helm/charts/goquorum-node/values.yaml
Covering both: Besu Node and GoQuorum Node
=> issue #187: Make AWS storage provisioning configurable via values.yaml file

docker/quorum-k8s-hooks/Dockerfile, helm/charts/besu-genesis/values.yaml, helm/charts/goquorum-genesis/values.yaml
`qgt-0.2.11` does not exist in [consensys/quorum-k8s-hooks](https://hub.docker.com/r/consensys/quorum-k8s-hooks/tags) and cannot pull the image.
=> Update qgt to 0.2.12

azure/scripts/bootstrap.sh
CSI chart's location has moved - as per https://github.com/Azure/secrets-store-csi-driver-provider-azure/tree/master/charts/csi-secrets-store-provider-azure#installation
=> Updated CSI chart location

helm/charts/besu-node/templates/node-storage.yaml, helm/charts/goquorum-node/templates/node-storage.yaml
refer to https://learn.microsoft.com/ko-kr/azure/aks/azure-csi-files-storage-provision
use "file.csi.azure.com".
but, "kubernetes.io/azure-file" if aks version is less than 1.21
I have tested this changes in my AKS 1.27.7
closes #219
=> update: azure files provisioner

playground/kubectl/quorum-besu/ibft2/README.md
The link to the network creation tutorial using the IBFT2 algorithm was incorrect. The commit fixes the link by updating to the correct link.
=> 📝 Update link to IBFT2 network creation tutorial

helm/charts/goquorum-node/templates/node-statefulset.yaml
Encountered an error with Helm installation when the `cloudNativeServices` option was enabled and the provider is aws. 
```
cluster:
provider: 'aws'
cloudNativeServices: true
```
secretProviderClass not found errors
```{bash}
Warning  FailedMount  4m57s (x72 over 135m)  kubelet  MountVolume.SetUp failed for volume "secrets-store" : rpc error: code = Unknown desc = failed to get secretproviderclass quorum/goquorum-node-validator-1-azure-secret-provider, error: SecretProviderClass.secrets-store.csi.x-k8s.io "goquorum-node-validator-1-azure-secret-provider" not found
```
edit secret-provider-class `{{ .Values.cluster.provider }}`
=> chore: fix secretProviderClass not found errors

helm/charts/besu-genesis/templates/genesis-job-cleanup.yaml, helm/charts/besu-genesis/templates/genesis-job-init.yaml, helm/charts/besu-node/templates/node-hooks-pre-delete.yaml, helm/charts/besu-node/templates/node-hooks-pre-install.yaml, helm/charts/besu-node/templates/node-hooks-service-account.yaml
The current besu charts fail to install for the `local` cluster.
This PR fixes `serviceAccountName` and assigns `hook-weight` for hook RoleBinding is created in order.
=> Fix besu chart errors

helm/charts/besu-genesis/templates/genesis-job-init.yaml, helm/charts/besu-node/templates/node-hooks-pre-delete.yaml, helm/charts/besu-node/templates/node-hooks-pre-install.yaml, helm/charts/goquorum-genesis/templates/genesis-job-init.yaml, helm/charts/goquorum-node/templates/node-hooks-pre-delete.yaml, helm/charts/goquorum-node/templates/node-hooks-pre-install.yaml
Current  'az login' settings get the error. 
This PR resolves the 'az login' error for workload Identity.
I have tested these changes in my AKS. 
refer to https://github.com/Azure/azure-cli/issues/26858
closes #224
=> fix: az login error

azure/scripts/bootstrap.sh, helm/charts/besu-genesis/templates/genesis-job-init.yaml, helm/charts/besu-node/templates/azure-secret-provider-class.yaml, helm/charts/besu-node/templates/node-hooks-pre-delete.yaml, helm/charts/besu-node/values.yaml, helm/values/bootnode.yml, helm/values/reader.yml, helm/values/txnode.yml, helm/values/validator.yml
There are a couple of changes in this PR I made to enable a smooth install on azure aks:
- position of `az aks get credentials` seemed wrong in the bootstrap script as its trying to create a manifest before it has the creds
- the `$AZURE_CLIENT_ID` used during `az login` in the pre/post hooks contains the full resource id in azure, not the user managed identity's client id.  Changed to pull it from the values file
- the azure secret provider class needs to use the managed identity from the cluster's node pool
=> Azure fixes - setting correct client ids

azure/README.md, helm/README.md, helm/charts/besu-node/values.yaml
- Corrected "make use some" to "make use of some" in the Azure README.md.
- Fixed spelling of "tha" to "that" in the Azure README.md.
- Corrected "DISABE_AUTH" to "DISABLE_AUTH" in the helm README.md.
- Fixed "becuase" to "because" in the values.yaml file.
=> Fix typos in README.md and values.yaml
